services:
  frontend:
    build:
      context: ./frontend
    tty: true
    stdin_open: true
    ports:
      - 8081:8081
      - 19000:19000
      - 19001:19001
      - 19002:19002
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_TRANSLATION_MODEL=qwen2.5:7b
